version: "3.8"
services:
  santa-backend:
    container_name: santa-app
    build: .
    ports:
      - "80:8080"
    volumes:
      - ./application.properties:/app/application.properties
    restart: always
